//Name: Evan Luo
//Date: July 23
//Title: Lesson1ZeroOne
//Purpose: to create a lesson panel with practice questions for lesson 1
// *** COMMENTING FOR THIS FILE AS WELL AS Lesson2Negative, Lesson3MultiplicationAndDivision, and Lesson4PowerRules IS THE SAME; ONLY NEED TO READ ONE ***

package TutorialApp;

public class Lesson1ZeroOne extends javax.swing.JPanel {

    //create constants for the multiple choice section of the lesson
    public static final String CORRECT_MESSAGE = "Great! You got the correct answer!";  //define correct answer constant and assign message for correct answer 
    public static final String WRONG_MESSAGE = "Wrong answer. Please try again!";  //define wrong answer constant and assign message for wrong answer
    public static final String NOSELECT_MESSAGE = "You didn't select an answer!";  //define no answer constant and assigning message for no answer selected
    public static final String MULTIPLESELECT_MESSAGE = "Multiple answers selected, please select only one!";  //define multiple selection constant and assign message for multiple answers selected
    
    public Lesson1ZeroOne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        lblLesson1Practice = new javax.swing.JLabel();
        lblZeroRule = new javax.swing.JLabel();
        lblQuestion1 = new javax.swing.JLabel();
        chkChoice11 = new javax.swing.JCheckBox();
        chkChoice12 = new javax.swing.JCheckBox();
        chkChoice13 = new javax.swing.JCheckBox();
        btnAnswer1 = new javax.swing.JButton();
        lblSystemAnswer1 = new javax.swing.JLabel();
        lblQuestion2 = new javax.swing.JLabel();
        chkChoice21 = new javax.swing.JCheckBox();
        chkChoice22 = new javax.swing.JCheckBox();
        chkChoice23 = new javax.swing.JCheckBox();
        lblSystemAnswer2 = new javax.swing.JLabel();
        lblLesson1Content = new javax.swing.JLabel();
        lblZeroDesc1 = new javax.swing.JLabel();
        lblZeroDesc2 = new javax.swing.JLabel();
        lblZeroDesc3 = new javax.swing.JLabel();
        lblOneRule = new javax.swing.JLabel();
        lblOneDesc1 = new javax.swing.JLabel();
        lblOneDesc2 = new javax.swing.JLabel();
        lblLesson1Title = new javax.swing.JLabel();
        btnAnswer2 = new javax.swing.JButton();

        lblLesson1Practice.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblLesson1Practice.setForeground(new java.awt.Color(0, 0, 204));
        lblLesson1Practice.setText("PRACTICE");

        lblZeroRule.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblZeroRule.setText("Zero Rule");

        lblQuestion1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblQuestion1.setText("<html>1. What is the value of 87954389042878572389<sup>0</sup>?</html>");

        chkChoice11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice11.setText("  1");
        chkChoice11.setActionCommand("zxdgfsdsdgsssssssssssssssssssssssssssssssssssssssssss");

        chkChoice12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice12.setText("  87954389042878572389");

        chkChoice13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice13.setText("  0");

        btnAnswer1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAnswer1.setText("Submit");
        btnAnswer1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 255), new java.awt.Color(153, 153, 153)));
        btnAnswer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswer1ActionPerformed(evt);
            }
        });

        lblSystemAnswer1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblSystemAnswer1.setForeground(new java.awt.Color(204, 51, 0));

        lblQuestion2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblQuestion2.setText("<html>2. What would the value of 2 X 8<sup>1</sup>?</html>");

        chkChoice21.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice21.setText("  0");
        chkChoice21.setActionCommand("zxdgfsdsdgsssssssssssssssssssssssssssssssssssssssssss");

        chkChoice22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice22.setText("  16");

        chkChoice23.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice23.setText("  2");

        lblSystemAnswer2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblSystemAnswer2.setForeground(new java.awt.Color(204, 51, 0));

        lblLesson1Content.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblLesson1Content.setForeground(new java.awt.Color(0, 0, 204));
        lblLesson1Content.setText("CONTENT");

        lblZeroDesc1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblZeroDesc1.setText("Any number with exponent zero will be equal to 1. ");

        lblZeroDesc2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblZeroDesc2.setText("Emphasis on ANY, even the biggest of numbers.");

        lblZeroDesc3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblZeroDesc3.setText("<html>For example, 20043289423798247<sup>0</sup></html> = 1");

        lblOneRule.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblOneRule.setText("One Rule");

        lblOneDesc1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblOneDesc1.setText("Any number with exponent one will be equal to themselves. ");

        lblOneDesc2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblOneDesc2.setText("<html>For example, 20438<sup>1</sup>  = 20438 and 1<sup>1</sup> = 1.</thml>");

        lblLesson1Title.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblLesson1Title.setForeground(new java.awt.Color(204, 51, 0));
        lblLesson1Title.setText("LESSON 1");

        btnAnswer2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAnswer2.setText("Submit");
        btnAnswer2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 255), new java.awt.Color(153, 153, 153)));
        btnAnswer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswer2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLesson1Content)
                    .addComponent(lblLesson1Title)
                    .addComponent(lblZeroRule)
                    .addComponent(lblZeroDesc1)
                    .addComponent(lblZeroDesc2)
                    .addComponent(lblZeroDesc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOneRule)
                    .addComponent(lblOneDesc1)
                    .addComponent(lblOneDesc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkChoice11)
                    .addComponent(chkChoice12)
                    .addComponent(chkChoice13)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(btnAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSystemAnswer1))
                    .addComponent(chkChoice21)
                    .addComponent(chkChoice22)
                    .addComponent(chkChoice23)
                    .addComponent(lblQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(btnAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSystemAnswer2))
                    .addComponent(lblLesson1Practice)
                    .addComponent(lblQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(chkChoice11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkChoice12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkChoice13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSystemAnswer1))
                        .addGap(57, 57, 57)
                        .addComponent(lblQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(chkChoice21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkChoice22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkChoice23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSystemAnswer2)))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLesson1Title)
                            .addComponent(lblLesson1Practice))
                        .addGap(18, 18, 18)
                        .addComponent(lblLesson1Content)
                        .addGap(18, 18, 18)
                        .addComponent(lblZeroRule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblZeroDesc1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblZeroDesc2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblZeroDesc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(lblOneRule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOneDesc1)
                        .addGap(13, 13, 13)
                        .addComponent(lblOneDesc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //in the event that the first question's button has been clicked
    private void btnAnswer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnswer1ActionPerformed
        //declare string variable that will hold the final verdict of the user's answer and assign a blank message for now
        String strSystemAnswer="";
        
        //check if the user has checked off the first box (CORRECT ANSWER)
        if (chkChoice11.isSelected()) //isSelected() method to determining whether a checkbox is checked or not is retrieved from: https://stackoverflow.com/questions/3599908/how-to-check-that-a-jcheckbox-is-checked
        {
            //append result corresponding to first checkbox to the system answer string variable
            strSystemAnswer += ";"+ CORRECT_MESSAGE; //using ; as separator that will indicated whether there is more than one answer
            //constant will show the corresponding message
        }
        //check if the user has ticked the second choice/box (WRONG ANSWER)
        if (chkChoice12.isSelected())
        {
            //append result of second checkbox into system result string variable
            strSystemAnswer += ";"+ WRONG_MESSAGE;  //constant will show the corresponding message
        }
        //check whether the third check box has been selected (WRONG ANSWER)
        if (chkChoice13.isSelected())
        {
            //append verdict of third checkbox's answer into system result variable 
            strSystemAnswer += ";"+ WRONG_MESSAGE;  //constant will show the corresponding message
        }
        //check if user has selected an answer
        if (strSystemAnswer.length() >0)  //length() method verifies that the answer is not blank
        {
            //use substring() method to trim out the first separator ";"
            strSystemAnswer= strSystemAnswer.substring(1, strSystemAnswer.length());
        }
        //if no checkbox has been selected
        if (strSystemAnswer == "") //making a string comparision with == to see if the data stored within the string variable is blank
        {
            //display message that no choice has been selected
            strSystemAnswer= NOSELECT_MESSAGE; //constant will show the corresponding message
        }
        //if user has checked off more than one box
        if (strSystemAnswer.indexOf(";")>=0) //checks for the position of a ; as there will be a non-trimmed out one if there are two answers selected
        {
            //display message that multiple choices have been selected
            strSystemAnswer= MULTIPLESELECT_MESSAGE;  //constant will show the corresponding message
        }
        
        //display corresponding message to user through the label by the setText() method
        lblSystemAnswer1.setText(strSystemAnswer);
    }//GEN-LAST:event_btnAnswer1ActionPerformed

    //in the event that the second question's button has been clicked
    private void btnAnswer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnswer2ActionPerformed
        //declare string variable that will hold the final verdict of the user's answer and assign a blank message for now
        String strSystemAnswer="";
        
        //check if the user has checked off the first box (WRONG ANSWER)
        if (chkChoice21.isSelected()) //isSelected() method to determining whether a checkbox is checked or not is retrieved from: https://stackoverflow.com/questions/3599908/how-to-check-that-a-jcheckbox-is-checked
        {
            //append result corresponding to first checkbox to the system answer string variable
            strSystemAnswer += ";"+ WRONG_MESSAGE; //using ; as separator that will indicated whether there is more than one answer in a later if statement
            //constant will show the corresponding message
        }
        //check if the user has ticked the second choice/box (CORRECT ANSWER)
        if (chkChoice22.isSelected())
        {
            //append result of second checkbox into system result string variable
            strSystemAnswer += ";"+ CORRECT_MESSAGE;  //using ; as separator that will indicated whether there is more than one answer in a later if statement
            //constant will show the corresponding message
        }
        //check whether the third check box has been selected (WRONG ANSWER)
        if (chkChoice23.isSelected())
        {
            //append verdict of third checkbox's answer into system result variable 
            strSystemAnswer += ";"+ WRONG_MESSAGE;  //using ; as separator that will indicate whether there is more than one answer in a later if statement
            //constant will show the corresponding message
        }
        //check if user has selected an answer
        if (strSystemAnswer.length() >0)  //length() method verifies that the answer is not blank
        {
            //use substring() method to trim out the first separator ";"
            strSystemAnswer= strSystemAnswer.substring(1, strSystemAnswer.length());
        }
        //if no checkbox has been selected
        if (strSystemAnswer == "") //making a string comparision with == to see if the data stored within the string variable is blank
        {
            //display message that no choice has been selected
            strSystemAnswer= NOSELECT_MESSAGE; //constant will show the corresponding message
        }
        //if user has checked off more than one box
        if (strSystemAnswer.indexOf(";")>=0) //checks for the position of a ; with indexOf() as there will be a non-trimmed out one if there are two answers selected
        {
            //display message that multiple choices have been selected
            strSystemAnswer= MULTIPLESELECT_MESSAGE;  //constant will show the corresponding message
        }
        
        //display corresponding message to user through the label by the setText() method
        lblSystemAnswer2.setText(strSystemAnswer);
    }//GEN-LAST:event_btnAnswer2ActionPerformed

    //this section is the autogenerated variable declaration of the GUI components
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnswer1;
    private javax.swing.JButton btnAnswer2;
    private javax.swing.JCheckBox chkChoice11;
    private javax.swing.JCheckBox chkChoice12;
    private javax.swing.JCheckBox chkChoice13;
    private javax.swing.JCheckBox chkChoice21;
    private javax.swing.JCheckBox chkChoice22;
    private javax.swing.JCheckBox chkChoice23;
    private javax.swing.JLabel lblLesson1Content;
    private javax.swing.JLabel lblLesson1Practice;
    private javax.swing.JLabel lblLesson1Title;
    private javax.swing.JLabel lblOneDesc1;
    private javax.swing.JLabel lblOneDesc2;
    private javax.swing.JLabel lblOneRule;
    private javax.swing.JLabel lblQuestion1;
    private javax.swing.JLabel lblQuestion2;
    private javax.swing.JLabel lblSystemAnswer1;
    private javax.swing.JLabel lblSystemAnswer2;
    private javax.swing.JLabel lblZeroDesc1;
    private javax.swing.JLabel lblZeroDesc2;
    private javax.swing.JLabel lblZeroDesc3;
    private javax.swing.JLabel lblZeroRule;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}

/*
*Bibliography:
*How to check that a JCheckBox is checked? (n.d.). Retrieved July 22, 2018, from https://stackoverflow.com/questions/3599908/how-to-check-that-a-jcheckbox-is-checked
*/