//Name: Evan Luo
//Date: July 23
//Title: Lesson2Negative
//Purpose: to create a lesson panel with practice questions for lesson 2
// *** COMMENTING FOR THIS FILE AS WELL AS Lesson1ZeroOne, Lesson3MultiplicationAndDivision, and Lesson4PowerRules IS THE SAME; ONLY NEED TO READ ONE ***

package TutorialApp;

public class Lesson2Negative extends javax.swing.JPanel {
    
    //create constants for the multiple choice section of the lesson
    public static final String CORRECT_MESSAGE = "Great! You got the correct answer!";  //define correct answer constant and assign message for correct answer 
    public static final String WRONG_MESSAGE = "Wrong answer. Please try again!";  //define wrong answer constant and assign message for wrong answer
    public static final String NOSELECT_MESSAGE = "You didn't select an answer!";  //define no answer constant and assigning message for no answer selected
    public static final String MULTIPLESELECT_MESSAGE = "Multiple answers selected, please select only one!";  //define multiple selection constant and assign message for multiple answers selected

    public Lesson2Negative() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        lblLesson2Practice = new javax.swing.JLabel();
        lblNegativeRule = new javax.swing.JLabel();
        lblQuestion1 = new javax.swing.JLabel();
        chkChoice11 = new javax.swing.JCheckBox();
        chkChoice12 = new javax.swing.JCheckBox();
        chkChoice13 = new javax.swing.JCheckBox();
        btnAnswer1 = new javax.swing.JButton();
        lblSystemAnswer1 = new javax.swing.JLabel();
        lblQuestion2 = new javax.swing.JLabel();
        chkChoice21 = new javax.swing.JCheckBox();
        chkChoice22 = new javax.swing.JCheckBox();
        chkChoice23 = new javax.swing.JCheckBox();
        lblSystemAnswer2 = new javax.swing.JLabel();
        lblLesson2Content = new javax.swing.JLabel();
        lblNegativeDesc1 = new javax.swing.JLabel();
        lblNegativeDesc2 = new javax.swing.JLabel();
        lblNegativeDesc4 = new javax.swing.JLabel();
        lblLesson2Title = new javax.swing.JLabel();
        btnAnswer2 = new javax.swing.JButton();
        lblNegativeDesc5 = new javax.swing.JLabel();
        lblNegativeDesc6 = new javax.swing.JLabel();
        lblNegativeImage = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 2000));

        lblLesson2Practice.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblLesson2Practice.setForeground(new java.awt.Color(0, 0, 204));
        lblLesson2Practice.setText("PRACTICE");

        lblNegativeRule.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNegativeRule.setText("Negative Exponents");

        lblQuestion1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblQuestion1.setText("<html>1. What is 2<sup>-1</sup> + 3<sup>0 </sup>- 2<sup>-2</sup>?</html>");

        chkChoice11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice11.setText("  5/12");
        chkChoice11.setActionCommand("zxdgfsdsdgsssssssssssssssssssssssssssssssssssssssssss");

        chkChoice12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice12.setText("  5/4");

        chkChoice13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice13.setText("  7");

        btnAnswer1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAnswer1.setText("Submit");
        btnAnswer1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 255), new java.awt.Color(153, 153, 153)));
        btnAnswer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswer1ActionPerformed(evt);
            }
        });

        lblSystemAnswer1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblSystemAnswer1.setForeground(new java.awt.Color(204, 51, 0));

        lblQuestion2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblQuestion2.setText("2. Which of the following is equivalent to 1/64?");

        chkChoice21.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice21.setText("<html>&nbsp 8<sup>-2</sup></html>");
        chkChoice21.setActionCommand("");

        chkChoice22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice22.setText("<html>&nbsp 8<sup>-8</sup></html>");

        chkChoice23.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice23.setText("<html>&nbsp 64<sup>-2</sup></html>");

        lblSystemAnswer2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblSystemAnswer2.setForeground(new java.awt.Color(204, 51, 0));

        lblLesson2Content.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblLesson2Content.setForeground(new java.awt.Color(0, 0, 204));
        lblLesson2Content.setText("CONTENT");

        lblNegativeDesc1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblNegativeDesc1.setText("The equivalent of a number to the power of a negative");

        lblNegativeDesc2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblNegativeDesc2.setText("number is  1 / number to the power of the positive version");

        lblNegativeDesc4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblNegativeDesc4.setText("of the power.");

        lblLesson2Title.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblLesson2Title.setForeground(new java.awt.Color(204, 51, 0));
        lblLesson2Title.setText("LESSON 2");

        btnAnswer2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAnswer2.setText("Submit");
        btnAnswer2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 255), new java.awt.Color(153, 153, 153)));
        btnAnswer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswer2ActionPerformed(evt);
            }
        });

        lblNegativeDesc5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblNegativeDesc5.setText("<html>For instance, 3<sup>-2 </sup>= 1/3<sup>2</sup> = 1/9</thml>");

        lblNegativeDesc6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblNegativeDesc6.setText("<html>This works the opposite way as well, 1/25 = 5<sup>-2</sup>.</html>");

        lblNegativeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TutorialApp/negativeJokeImage.PNG"))); // NOI18N

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNegativeDesc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLesson2Content)
                    .addComponent(lblLesson2Title)
                    .addComponent(lblNegativeDesc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNegativeRule)
                    .addComponent(lblNegativeDesc1)
                    .addComponent(lblNegativeDesc2)
                    .addComponent(lblNegativeDesc4)
                    .addComponent(lblNegativeImage))
                .addGap(60, 60, 60)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkChoice11)
                    .addComponent(chkChoice12)
                    .addComponent(chkChoice13)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(btnAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSystemAnswer1))
                    .addComponent(chkChoice23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(btnAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSystemAnswer2))
                    .addComponent(lblLesson2Practice)
                    .addComponent(lblQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkChoice21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkChoice22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(lblLesson2Title)
                        .addGap(18, 18, 18)
                        .addComponent(lblLesson2Content)
                        .addGap(18, 18, 18)
                        .addComponent(lblNegativeRule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNegativeDesc1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNegativeDesc2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNegativeDesc4)
                        .addGap(18, 18, 18)
                        .addComponent(lblNegativeDesc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNegativeDesc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNegativeImage))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(lblQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(chkChoice11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkChoice12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkChoice13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSystemAnswer1))
                                .addGap(57, 57, 57)
                                .addComponent(lblQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblLesson2Practice))
                        .addGap(3, 3, 3)
                        .addComponent(chkChoice21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(chkChoice22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkChoice23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSystemAnswer2))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

        //in the event that the first question's button has been clicked
    private void btnAnswer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnswer1ActionPerformed
        //declare string variable that will hold the final verdict of the user's answer and assign a blank message for now
        String strSystemAnswer="";
        
        //check if the user has checked off the first box (WRONG ANSWER)
        if (chkChoice11.isSelected()) //isSelected() method to determining whether a checkbox is checked or not is retrieved from: https://stackoverflow.com/questions/3599908/how-to-check-that-a-jcheckbox-is-checked
        {
            //append result corresponding to first checkbox to the system answer string variable
            strSystemAnswer += ";"+ WRONG_MESSAGE; //using ; as separator that will indicated whether there is more than one answer
            //constant will show the corresponding message
        }
        //check if the user has ticked the second choice/box (CORRECT ANSWER)
        if (chkChoice12.isSelected())
        {
            //append result of second checkbox into system result string variable
            strSystemAnswer += ";"+ CORRECT_MESSAGE;  //constant will show the corresponding message
        }
        //check whether the third check box has been selected (WRONG ANSWER)
        if (chkChoice13.isSelected())
        {
            //append verdict of third checkbox's answer into system result variable 
            strSystemAnswer += ";"+ WRONG_MESSAGE;  //constant will show the corresponding message
        }
        //check if user has selected an answer
        if (strSystemAnswer.length() >0)  //length() method verifies that the answer is not blank
        {
            //use substring() method to trim out the first separator ";"
            strSystemAnswer= strSystemAnswer.substring(1, strSystemAnswer.length());
        }
        //if no checkbox has been selected
        if (strSystemAnswer == "") //making a string comparision with == to see if the data stored within the string variable is blank
        {
            //display message that no choice has been selected
            strSystemAnswer= NOSELECT_MESSAGE; //constant will show the corresponding message
        }
        //if user has checked off more than one box
        if (strSystemAnswer.indexOf(";")>=0) //checks for the position of a ; as there will be a non-trimmed out one if there are two answers selected
        {
            //display message that multiple choices have been selected
            strSystemAnswer= MULTIPLESELECT_MESSAGE;  //constant will show the corresponding message
        }
        
        //display corresponding message to user through the label by the setText() method
        lblSystemAnswer1.setText(strSystemAnswer);
    }//GEN-LAST:event_btnAnswer1ActionPerformed

    //in the event that the second question's button has been clicked
    private void btnAnswer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnswer2ActionPerformed
        //declare string variable that will hold the final verdict of the user's answer and assign a blank message for now
        String strSystemAnswer="";
        
        //check if the user has checked off the first box (CORRECT ANSWER)
        if (chkChoice21.isSelected()) //isSelected() method to determining whether a checkbox is checked or not is retrieved from: https://stackoverflow.com/questions/3599908/how-to-check-that-a-jcheckbox-is-checked
        {
            //append result corresponding to first checkbox to the system answer string variable
            strSystemAnswer += ";"+ CORRECT_MESSAGE; //using ; as separator that will indicated whether there is more than one answer in a later if statement
            //constant will show the corresponding message
        }
        //check if the user has ticked the second choice/box (WRONG ANSWER)
        if (chkChoice22.isSelected())
        {
            //append result of second checkbox into system result string variable
            strSystemAnswer += ";"+ WRONG_MESSAGE;  //using ; as separator that will indicated whether there is more than one answer in a later if statement
            //constant will show the corresponding message
        }
        //check whether the third check box has been selected (WRONG ANSWER)
        if (chkChoice23.isSelected())
        {
            //append verdict of third checkbox's answer into system result variable 
            strSystemAnswer += ";"+ WRONG_MESSAGE;  //using ; as separator that will indicate whether there is more than one answer in a later if statement
            //constant will show the corresponding message
        }
        //check if user has selected an answer
        if (strSystemAnswer.length() >0)  //length() method verifies that the answer is not blank
        {
            //use substring() method to trim out the first separator ";"
            strSystemAnswer= strSystemAnswer.substring(1, strSystemAnswer.length());
        }
        //if no checkbox has been selected
        if (strSystemAnswer == "") //making a string comparision with == to see if the data stored within the string variable is blank
        {
            //display message that no choice has been selected
            strSystemAnswer= NOSELECT_MESSAGE; //constant will show the corresponding message
        }
        //if user has checked off more than one box
        if (strSystemAnswer.indexOf(";")>=0) //checks for the position of a ; with indexOf() as there will be a non-trimmed out one if there are two answers selected
        {
            //display message that multiple choices have been selected
            strSystemAnswer= MULTIPLESELECT_MESSAGE;  //constant will show the corresponding message
        }
        
        //display corresponding message to user through the label by the setText() method
        lblSystemAnswer2.setText(strSystemAnswer);
    }//GEN-LAST:event_btnAnswer2ActionPerformed

    //this section is the autogenerated variable declaration of the GUI components
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnswer1;
    private javax.swing.JButton btnAnswer2;
    private javax.swing.JCheckBox chkChoice11;
    private javax.swing.JCheckBox chkChoice12;
    private javax.swing.JCheckBox chkChoice13;
    private javax.swing.JCheckBox chkChoice21;
    private javax.swing.JCheckBox chkChoice22;
    private javax.swing.JCheckBox chkChoice23;
    private javax.swing.JLabel lblLesson2Content;
    private javax.swing.JLabel lblLesson2Practice;
    private javax.swing.JLabel lblLesson2Title;
    private javax.swing.JLabel lblNegativeDesc1;
    private javax.swing.JLabel lblNegativeDesc2;
    private javax.swing.JLabel lblNegativeDesc4;
    private javax.swing.JLabel lblNegativeDesc5;
    private javax.swing.JLabel lblNegativeDesc6;
    private javax.swing.JLabel lblNegativeImage;
    private javax.swing.JLabel lblNegativeRule;
    private javax.swing.JLabel lblQuestion1;
    private javax.swing.JLabel lblQuestion2;
    private javax.swing.JLabel lblSystemAnswer1;
    private javax.swing.JLabel lblSystemAnswer2;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}

/*
*Bibliography:
*How to check that a JCheckBox is checked? (n.d.). Retrieved July 22, 2018, from https://stackoverflow.com/questions/3599908/how-to-check-that-a-jcheckbox-is-checked
*/