//Name: Evan Luo
//Date: July 23
//Title: Lesson4PowerRules
//Purpose: to create a lesson panel with practice questions for lesson 4
// *** COMMENTING FOR THIS FILE AS WELL AS Lesson1ZeroOne, Lesson2Negative, and Lesson3MultiplicationAndDivision IS THE SAME; ONLY NEED TO READ ONE ***

package TutorialApp;

public class Lesson4PowerRules extends javax.swing.JPanel {

    //create constants for the multiple choice section of the lesson
    public static final String CORRECT_MESSAGE = "Great! You got the correct answer!";  //define correct answer constant and assign message for correct answer 
    public static final String WRONG_MESSAGE = "Wrong answer. Please try again!";  //define wrong answer constant and assign message for wrong answer
    public static final String NOSELECT_MESSAGE = "You didn't select an answer!";  //define no answer constant and assigning message for no answer selected
    public static final String MULTIPLESELECT_MESSAGE = "Multiple answers selected, please select only one!";  //define multiple selection constant and assign message for multiple answers selected
    
    public Lesson4PowerRules() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        lblLesson4Practice = new javax.swing.JLabel();
        lblQuestion1 = new javax.swing.JLabel();
        chkChoice11 = new javax.swing.JCheckBox();
        chkChoice12 = new javax.swing.JCheckBox();
        chkChoice13 = new javax.swing.JCheckBox();
        btnAnswer1 = new javax.swing.JButton();
        lblSystemAnswer1 = new javax.swing.JLabel();
        lblQuestion2 = new javax.swing.JLabel();
        chkChoice21 = new javax.swing.JCheckBox();
        chkChoice22 = new javax.swing.JCheckBox();
        chkChoice23 = new javax.swing.JCheckBox();
        lblSystemAnswer2 = new javax.swing.JLabel();
        lblLesson4Content = new javax.swing.JLabel();
        lblPowerDesc1 = new javax.swing.JLabel();
        lblPowerDesc2 = new javax.swing.JLabel();
        lblPowerDesc3 = new javax.swing.JLabel();
        lblExponentDesc2 = new javax.swing.JLabel();
        lblLesson4Title = new javax.swing.JLabel();
        btnAnswer2 = new javax.swing.JButton();
        lblPowerDesc4 = new javax.swing.JLabel();
        lblMultipleTermRule = new javax.swing.JLabel();
        lblPowerDesc5 = new javax.swing.JLabel();
        lblSingleTermRule1 = new javax.swing.JLabel();
        lblPowerDesc6 = new javax.swing.JLabel();
        lblPowerDesc7 = new javax.swing.JLabel();
        lblPowerDesc8 = new javax.swing.JLabel();
        lblPowerDesc9 = new javax.swing.JLabel();
        lblPowerDesc10 = new javax.swing.JLabel();

        lblLesson4Practice.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblLesson4Practice.setForeground(new java.awt.Color(0, 0, 204));
        lblLesson4Practice.setText("PRACTICE");

        lblQuestion1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblQuestion1.setText("<html>1. What is the value of (2<sup>2</sup> * 3)<sup>2</sup>?</html>");

        chkChoice11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice11.setText("  144");
        chkChoice11.setActionCommand("zxdgfsdsdgsssssssssssssssssssssssssssssssssssssssssss");

        chkChoice12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice12.setText("  12");

        chkChoice13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice13.setText("  48");

        btnAnswer1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAnswer1.setText("Submit");
        btnAnswer1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 255), new java.awt.Color(153, 153, 153)));
        btnAnswer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswer1ActionPerformed(evt);
            }
        });

        lblSystemAnswer1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblSystemAnswer1.setForeground(new java.awt.Color(204, 51, 0));

        lblQuestion2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblQuestion2.setText("<html>2. What would the value of (3<sup>2</sup> / 7)<sup>-1</sup> be?</html>");

        chkChoice21.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice21.setText("  9 / 7");
        chkChoice21.setActionCommand("zxdgfsdsdgsssssssssssssssssssssssssssssssssssssssssss");

        chkChoice22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice22.setText("<html>&nbsp 7 / 9</html>");

        chkChoice23.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chkChoice23.setText("  1 / 63");

        lblSystemAnswer2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblSystemAnswer2.setForeground(new java.awt.Color(204, 51, 0));

        lblLesson4Content.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblLesson4Content.setForeground(new java.awt.Color(0, 0, 204));
        lblLesson4Content.setText("CONTENT");

        lblPowerDesc1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPowerDesc1.setText("There are many distributive rules that exist to simplify");

        lblPowerDesc2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPowerDesc2.setText("mathematical expressions.  ");

        lblPowerDesc3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPowerDesc3.setText("bases of the multiplication or division.");

        lblLesson4Title.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblLesson4Title.setForeground(new java.awt.Color(204, 51, 0));
        lblLesson4Title.setText("LESSON 4");

        btnAnswer2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAnswer2.setText("Submit");
        btnAnswer2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 255), new java.awt.Color(153, 153, 153)));
        btnAnswer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswer2ActionPerformed(evt);
            }
        });

        lblPowerDesc4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPowerDesc4.setText("When an entire power is raised to another exponent, ");

        lblMultipleTermRule.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMultipleTermRule.setText("Multiple Term Distribution");

        lblPowerDesc5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPowerDesc5.setText("multiply the exponents and keep the same base.");

        lblSingleTermRule1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSingleTermRule1.setText("Single Term Distribution");

        lblPowerDesc6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPowerDesc6.setText("a number, distribute the exponent to each of the different");

        lblPowerDesc7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPowerDesc7.setText("When a multiplication or division is put to the exponent of");

        lblPowerDesc8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPowerDesc8.setText("<html>As an example, (2<sup>3</sup>/3<sup>4</sup>)<sup>2</sup> = 2<sup>6</sup> / 3<sup>8</sup></html>");

        lblPowerDesc9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPowerDesc9.setText("<html>For instance, (2<sup>3</sup>)<sup>2</sup> = 2<sup>6</sup>");

        lblPowerDesc10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblPowerDesc10.setText("<html>It works the same for multiplication, (2 * 3<sup>4</sup>)<sup>2</sup>=2<sup>2</sup>* 3<sup>8</sup> </html>");

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLesson4Content)
                            .addComponent(lblLesson4Title)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMultipleTermRule)
                                    .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPowerDesc3)
                                            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblPowerDesc8, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblPowerDesc6, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblPowerDesc10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(lblPowerDesc7)))
                                .addGap(23, 23, 23)
                                .addComponent(lblExponentDesc2))
                            .addComponent(lblPowerDesc1)
                            .addComponent(lblPowerDesc2)
                            .addComponent(lblSingleTermRule1)
                            .addComponent(lblPowerDesc4)
                            .addComponent(lblPowerDesc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSystemAnswer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSystemAnswer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPowerDesc5)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGap(582, 582, 582)
                                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkChoice21)
                                    .addComponent(chkChoice22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkChoice23)
                                    .addComponent(lblLesson4Practice)
                                    .addComponent(chkChoice11)
                                    .addComponent(chkChoice12)
                                    .addComponent(chkChoice13)
                                    .addComponent(lblQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 201, Short.MAX_VALUE)))
                .addGap(31, 31, 31))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLesson4Title)
                            .addComponent(lblLesson4Practice))
                        .addGap(18, 18, 18)
                        .addComponent(lblLesson4Content)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addComponent(lblExponentDesc2))
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblPowerDesc1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPowerDesc2)
                                .addGap(44, 44, 44)
                                .addComponent(lblSingleTermRule1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPowerDesc4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPowerDesc5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPowerDesc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSystemAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addComponent(chkChoice11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkChoice12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkChoice13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addComponent(lblQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkChoice21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addComponent(lblMultipleTermRule)
                                .addGap(18, 18, 18)
                                .addComponent(lblPowerDesc7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPowerDesc6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPowerDesc3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPowerDesc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPowerDesc10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addComponent(chkChoice22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkChoice23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSystemAnswer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAnswer2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnswer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnswer1ActionPerformed
        //declare string variable that will hold the final verdict of the user's answer and assign a blank message for now
        String strSystemAnswer="";
        
        //check if the user has checked off the first box (CORRECT ANSWER)
        if (chkChoice11.isSelected()) //isSelected() method to determining whether a checkbox is checked or not is retrieved from: https://stackoverflow.com/questions/3599908/how-to-check-that-a-jcheckbox-is-checked
        {
            //append result corresponding to first checkbox to the system answer string variable
            strSystemAnswer += ";"+ CORRECT_MESSAGE; //using ; as separator that will indicated whether there is more than one answer
            //constant will show the corresponding message
        }
        //check if the user has ticked the second choice/box (WRONG ANSWER)
        if (chkChoice12.isSelected())
        {
            //append result of second checkbox into system result string variable
            strSystemAnswer += ";"+ WRONG_MESSAGE;  //constant will show the corresponding message
        }
        //check whether the third check box has been selected (WRONG ANSWER)
        if (chkChoice13.isSelected())
        {
            //append verdict of third checkbox's answer into system result variable 
            strSystemAnswer += ";"+ WRONG_MESSAGE;  //constant will show the corresponding message
        }
        //check if user has selected an answer
        if (strSystemAnswer.length() >0)  //length() method verifies that the answer is not blank
        {
            //use substring() method to trim out the first separator ";"
            strSystemAnswer= strSystemAnswer.substring(1, strSystemAnswer.length());
        }
        //if no checkbox has been selected
        if (strSystemAnswer == "") //making a string comparision with == to see if the data stored within the string variable is blank
        {
            //display message that no choice has been selected
            strSystemAnswer= NOSELECT_MESSAGE; //constant will show the corresponding message
        }
        //if user has checked off more than one box
        if (strSystemAnswer.indexOf(";")>=0) //checks for the position of a ; as there will be a non-trimmed out one if there are two answers selected
        {
            //display message that multiple choices have been selected
            strSystemAnswer= MULTIPLESELECT_MESSAGE;  //constant will show the corresponding message
        }
        
        //display corresponding message to user through the label by the setText() method
        lblSystemAnswer1.setText(strSystemAnswer);
    }//GEN-LAST:event_btnAnswer1ActionPerformed
    
    //in the event that the second question's button has been clicked
    private void btnAnswer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnswer2ActionPerformed
        //declare string variable that will hold the final verdict of the user's answer and assign a blank message for now
        String strSystemAnswer="";
        
        //check if the user has checked off the first box (WRONG ANSWER)
        if (chkChoice21.isSelected()) //isSelected() method to determining whether a checkbox is checked or not is retrieved from: https://stackoverflow.com/questions/3599908/how-to-check-that-a-jcheckbox-is-checked
        {
            //append result corresponding to first checkbox to the system answer string variable
            strSystemAnswer += ";"+ WRONG_MESSAGE; //using ; as separator that will indicated whether there is more than one answer in a later if statement
            //constant will show the corresponding message
        }
        //check if the user has ticked the second choice/box (CORRECT ANSWER)
        if (chkChoice22.isSelected())
        {
            //append result of second checkbox into system result string variable
            strSystemAnswer += ";"+ CORRECT_MESSAGE;  //using ; as separator that will indicated whether there is more than one answer in a later if statement
            //constant will show the corresponding message
        }
        //check whether the third check box has been selected (WRONG ANSWER)
        if (chkChoice23.isSelected())
        {
            //append verdict of third checkbox's answer into system result variable 
            strSystemAnswer += ";"+ WRONG_MESSAGE;  //using ; as separator that will indicate whether there is more than one answer in a later if statement
            //constant will show the corresponding message
        }
        //check if user has selected an answer
        if (strSystemAnswer.length() >0)  //length() method verifies that the answer is not blank
        {
            //use substring() method to trim out the first separator ";"
            strSystemAnswer= strSystemAnswer.substring(1, strSystemAnswer.length());
        }
        //if no checkbox has been selected
        if (strSystemAnswer == "") //making a string comparision with == to see if the data stored within the string variable is blank
        {
            //display message that no choice has been selected
            strSystemAnswer= NOSELECT_MESSAGE; //constant will show the corresponding message
        }
        //if user has checked off more than one box
        if (strSystemAnswer.indexOf(";")>=0) //checks for the position of a ; with indexOf() as there will be a non-trimmed out one if there are two answers selected
        {
            //display message that multiple choices have been selected
            strSystemAnswer= MULTIPLESELECT_MESSAGE;  //constant will show the corresponding message
        }
        
        //display corresponding message to user through the label by the setText() method
        lblSystemAnswer2.setText(strSystemAnswer);
    }//GEN-LAST:event_btnAnswer2ActionPerformed

    //this section is the autogenerated variable declaration of the GUI components
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnswer1;
    private javax.swing.JButton btnAnswer2;
    private javax.swing.JCheckBox chkChoice11;
    private javax.swing.JCheckBox chkChoice12;
    private javax.swing.JCheckBox chkChoice13;
    private javax.swing.JCheckBox chkChoice21;
    private javax.swing.JCheckBox chkChoice22;
    private javax.swing.JCheckBox chkChoice23;
    private javax.swing.JLabel lblExponentDesc2;
    private javax.swing.JLabel lblLesson4Content;
    private javax.swing.JLabel lblLesson4Practice;
    private javax.swing.JLabel lblLesson4Title;
    private javax.swing.JLabel lblMultipleTermRule;
    private javax.swing.JLabel lblPowerDesc1;
    private javax.swing.JLabel lblPowerDesc10;
    private javax.swing.JLabel lblPowerDesc2;
    private javax.swing.JLabel lblPowerDesc3;
    private javax.swing.JLabel lblPowerDesc4;
    private javax.swing.JLabel lblPowerDesc5;
    private javax.swing.JLabel lblPowerDesc6;
    private javax.swing.JLabel lblPowerDesc7;
    private javax.swing.JLabel lblPowerDesc8;
    private javax.swing.JLabel lblPowerDesc9;
    private javax.swing.JLabel lblQuestion1;
    private javax.swing.JLabel lblQuestion2;
    private javax.swing.JLabel lblSingleTermRule1;
    private javax.swing.JLabel lblSystemAnswer1;
    private javax.swing.JLabel lblSystemAnswer2;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}

/*
*Bibliography:
*How to check that a JCheckBox is checked? (n.d.). Retrieved July 22, 2018, from https://stackoverflow.com/questions/3599908/how-to-check-that-a-jcheckbox-is-checked
*/